drop table schedule;
drop table trip;
drop table train;

create table train (
    train_id integer not null primary key 
    generated by default as identity,
    lid integer not null,
    direction varchar(10) not null,
    start_date date not null,
    end_date date not null,
    start_time time not null,
    end_time time not null,
    interval time, --repeating trip has interval, for single trip interval is null
    foreign key (lid) references linie
);

create table trip (
    trip_id integer not null primary key
    generated by default as identity,
    train_id integer not null,
    departure_datetime seconddate not null,
    foreign key (train_id) references train
);

create table schedule (
    trip_id integer not null,
    hid integer not null,
    transit_datetime seconddate not null, --date and time when train is passing through station
    foreign key (trip_id) references trip,
    foreign key (hid) references haltestelle
);